#!/bin/sh

STRANGE_HOME="$HOME/.config/strange"
STRANGE_FLAGS=""
for ARG in "$@"; do
	if case $ARG in -*) true;; *) false;; esac; then
		STRANGE_FLAGS="$STRANGE_FLAGS $ARG"

	elif [ -f "$ARG" ]; then
		TRIE="$(echo "$ARG" | awk -F'/' ' { printf $NF; }' | awk -F'.' ' { for( i = 1; i <= NF; ++i) if ($i != "") {print $i; break;} }').trie"
		if [ -f "$STRANGE_HOME/$TRIE" ]; then
			echo "Incrementally learning into $TRIE: $ARG"
			LOAD_TRIE="-load=$STRANGE_HOME/$TRIE"
		else
			echo "First time learning into $TRIE: $ARG"
			mkdir -p "$STRANGE_HOME"
		fi

		strange $STRANGE_FLAGS "$LOAD_TRIE" -learn="$ARG" -save-compact="$STRANGE_HOME/$TRIE"
		EC=$?
		if [ $EC -ne 0 ]; then
			echo "ErrorCode $EC for $ARG" 1>&2
		fi

	else
		echo "No such file: $ARG" 1>&2
	fi
done
